-- Generated by the database client.
CREATE TABLE agent_memory (
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    user_id text NOT NULL,
    content text NOT NULL,
    embedding vector,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_agent_memory_user_id ON agent_memory USING btree ("user_id");

-- Generated by the database client.
CREATE TABLE rag_eval_diagnoses (
    id SERIAL NOT NULL,
    eval_run_id varchar(64) NOT NULL,
    sample_id varchar(64) NOT NULL,
    sample_batch_id integer NOT NULL DEFAULT 1,
    bad_case_rank integer NOT NULL,
    predicted_category varchar(128) NOT NULL DEFAULT ''::character varying,
    diagnosis_model varchar(128) NOT NULL DEFAULT ''::character varying,
    diagnosis text NOT NULL,
    diagnosis_markdown text NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    contexts jsonb NOT NULL DEFAULT '[]'::jsonb,
    ground_truth text NOT NULL,
    ground_truth_contexts jsonb NOT NULL DEFAULT '[]'::jsonb,
    faithfulness double precision NOT NULL DEFAULT 0,
    answer_relevancy double precision NOT NULL DEFAULT 0,
    context_precision double precision NOT NULL DEFAULT 0,
    context_recall double precision NOT NULL DEFAULT 0,
    avg_score double precision NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_rag_eval_diagnoses_eval_run_id ON rag_eval_diagnoses USING btree ("eval_run_id");

CREATE INDEX idx_rag_eval_diagnoses_batch ON rag_eval_diagnoses USING btree ("sample_batch_id");

CREATE INDEX idx_rag_eval_diagnoses_bad_case_rank ON rag_eval_diagnoses USING btree ("bad_case_rank");

CREATE INDEX idx_rag_eval_diagnoses_sample_id ON rag_eval_diagnoses USING btree ("sample_id");

-- Generated by the database client.
CREATE TABLE rag_eval_results (
    id SERIAL NOT NULL,
    eval_run_id varchar(64) NOT NULL,
    sample_id varchar(64) NOT NULL,
    sample_batch_id integer NOT NULL DEFAULT 1,
    question text NOT NULL,
    answer text NOT NULL,
    contexts jsonb NOT NULL DEFAULT '[]'::jsonb,
    ground_truth text NOT NULL,
    ground_truth_contexts jsonb NOT NULL DEFAULT '[]'::jsonb,
    faithfulness double precision NOT NULL DEFAULT 0,
    answer_relevancy double precision NOT NULL DEFAULT 0,
    context_precision double precision NOT NULL DEFAULT 0,
    context_recall double precision NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_rag_eval_results_eval_run_id ON rag_eval_results USING btree ("eval_run_id");

CREATE INDEX idx_rag_eval_results_batch ON rag_eval_results USING btree ("sample_batch_id");

CREATE INDEX idx_rag_eval_results_sample_id ON rag_eval_results USING btree ("sample_id");

-- Generated by the database client.
CREATE TABLE rag_eval_samples (
    id varchar(64) NOT NULL,
    category varchar(64) NOT NULL,
    difficulty varchar(16) NOT NULL,
    query text NOT NULL,
    ground_truth_context json NOT NULL,
    ground_truth_answer text NOT NULL,
    source_document varchar(255),
    metadata json NOT NULL,
    source_chunk_index integer NOT NULL,
    source_backend varchar(32) NOT NULL,
    created_at bigint NOT NULL,
    model_name varchar(128),
    batch_id integer NOT NULL DEFAULT 1,
    question text,
    ground_truth text,
    ground_truth_contexts jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX idx_rag_eval_samples_difficulty ON rag_eval_samples USING btree ("difficulty");

CREATE INDEX idx_rag_eval_samples_created_at ON rag_eval_samples USING btree ("created_at");

CREATE INDEX idx_rag_eval_samples_category ON rag_eval_samples USING btree ("category");

CREATE INDEX idx_rag_eval_samples_batch_id ON rag_eval_samples USING btree ("batch_id");